// =================================== EMPLOYEES =================================== //
TRACE # Load employees;

[Employees]:
	LOAD 
	[%Employee_key],
	[Employee.DatabaseType],
	[Employee.ID],
	[Employee.Current Manager ID],
	[Employee.Current Manager],
	[Employee.Name],
	[Employee.Sur name],
	[Employee.First name],
	[Employee.Middle name],
	[Employee.Gender Code],
	[Employee.Gender Dutch],
	[Employee.Gender English],
	[Employee.Job title],
	[Employee.Costcenter],
	[Employee.Costcenterlabel],
	[Employee.Age],
	[Employee.Age group Dutch],
	[Employee.Age group English],
	[Employee.Length of Service],
	[Employee.Start Date],
	[Employee.End Date],
	[Employee.Contract End Date],
	[Employee.Birth Date],
	[Employee.Status Code],
	[Employee.Status English],
	[Employee.Status Dutch],
	[Employee.Type Code],
	[Employee.Type English],
	[Employee.Type Dutch],
	[Employee.Marital State Code],
	[Employee.Marital State English],
	[Employee.Marital State Dutch],
	[Employee.Current FTE],
	[Employee.Freefield1],
	[Employee.Freefield2],
	[Employee.Freefield3],
	[Employee.Freefield4],
	[Employee.Freefield5],
	[Employee.Freefield6],
	[Employee.Freefield7],
	[Employee.Freefield8],
	[Employee.Freefield9],
	[Employee.Freefield10],
	[Employee.Freefield11],
	[Employee.Freefield12],
	[Employee.Freefield13],
	[Employee.Freefield14],
	[Employee.Freefield15],
	[Employee.Address1],
	[Employee.Zipcode],
	[Employee.City],
	[Employee.Telnr_privat1],
	[Employee.Telnr_privat2],
	[Employee.Telnr_work1],
	[Employee.Telnr_work2],
	[Employee.Company],
	[Employee.Company description],
	[Employee.Division],
	[Employee.JobgroupCode],
	[Employee.JobgroupDescription],
	[Employee.Service5Years],
	[Employee.Service10Years],
	[Employee.Service12halfYears],
	[Employee.Service15Years],
	[Employee.Service20Years],
	[Employee.Service25Years],
	[Employee.Service30Years],
	[Employee.Service40Years],
	[Employee.Service50Years],
	[Employee.CostcenterDescription],
	[Employee.CostcenterGroup01],
	[Employee.CostcenterGroup01Description],
	[Employee.CostcenterGroup02],
	[Employee.CostcenterGroup02Description],
	[Employee.CostcenterGroup03],
	[Employee.CostcenterGroup03Description],
	[Employee.CostcenterGroup04],
	[Employee.CostcenterGroup04Description]
	FROM $(vDirectory_Dimensions)\*_Employees.qvd (qvd);
	
